export const GETMEN_REQUEST = "GETMEN_REQUEST";
export const GETMEN_SUCCESS = "GETMEN_SUCCESS";
export const GETMEN_FAILURE = "GETMEN_FAILURE";

export const GETWOMEN_REQUEST = "GETWOMEN_REQUEST";
export const GETWOMEN_SUCCESS = "GETWOMEN_SUCCESS";
export const GETWOMEN_FAILURE = "GETWOMEN_FAILURE";